#logging.level.com.minascafe=DEBUG

spring.profiles.active=dev
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

#MySQL
spring.datasource.url= jdbc:mysql://localhost:3306/minas_cafe
spring.datasource.username=root
spring.datasource.password=359423
